version: "3.1"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - "start-dev"

  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer@123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#  back-end:
#    image: mouhamedniang/keycloak-spring-boot-3:0.0.1-SNAPSHOT
#    container_name: keycloak-spring-boot-3
#    ports:
#      - 8889:8889
#    restart: unless-stopped
#    environment:
#      spring.datasource.url: jdbc:postgresql://localhost:5432/school_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
#      spring.datasource.username: postgres
#      spring.datasource.password: passer@123
#      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64MXX:MaxMetaspaceSize=128M -Xmx64M
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    profile:
 #     -all

  redis:
    image: redis:7.2.3-alpine
    container_name: school-redis
    ports:
      - "6379:6379"


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: